name: Python Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        
    - name: Run Python script
      run: python script.py
      
    - name: Build executable with PyInstaller
      run: pyinstaller wifi_pc_info.spec
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: wifi-password-harvester-windows
        path: dist/wifi_pc_info.exe
        retention-days: 30
        
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        
    - name: Lint with flake8
      run: |
        flake8 script.py --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 script.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
